zenodo/modules/github/debug.py
zenodo/modules/github/upload.py

* Adds tools for easier debugging of GitHub payloads.

github: debug payload tools

---

zenodo/modules/deposit/forms.py

* Fixes issue with autocomplete not working any longer.

deposit: autocomplete fix

---

.travis.yml
zenodo/base/static/js/settings.js

* Adds path to `jquery.ui`. (closes #222)

base: fix shippable build

---

setup.py
zenodo/base/utils/bibtex.py

* Renames requirement to `kwalitee`. (closes #158)

global: fix Invenio-Kwalitee requirement

---

setup.py
zenodo/base/utils/bibtex.py
zenodo/config.py

* Removes duplicated oai-identifier. (closes #228)

global: duplicated oai-identifier fix

---

zenodo/base/format_elements/bfe_openaire_access_rights.py
zenodo/base/templates/records/_filepanel.html
zenodo/base/templates/records/base.html
zenodo/modules/accessrequests/errors.py
zenodo/modules/accessrequests/forms.py
zenodo/modules/accessrequests/helpers.py
zenodo/modules/accessrequests/models.py
zenodo/modules/accessrequests/signals.py
zenodo/modules/accessrequests/templates/accessrequests/access_request_base.html
zenodo/modules/accessrequests/templates/accessrequests/emails/accepted.tpl
zenodo/modules/accessrequests/templates/accessrequests/emails/confirmation.tpl
zenodo/modules/accessrequests/templates/accessrequests/emails/rejected.tpl
zenodo/modules/accessrequests/templates/accessrequests/settings/index_base.html
zenodo/modules/accessrequests/testsuite/helpers.py
zenodo/modules/accessrequests/testsuite/test_forms.py
zenodo/modules/accessrequests/testsuite/test_helpers.py
zenodo/modules/accessrequests/testsuite/test_models.py
zenodo/modules/accessrequests/testsuite/test_receivers.py
zenodo/modules/accessrequests/testsuite/test_tokens.py
zenodo/modules/accessrequests/tokens.py
zenodo/modules/accessrequests/views/__init__.py
zenodo/modules/accessrequests/views/requests.py
zenodo/modules/accessrequests/views/settings.py
zenodo/modules/accessrequests/widgets.py

* Cleans up access request module after feedback (closes #221).
* Adds maximum expiry date for link expiration.
* Changes wording of end-user text.
* Changes color of restricted access label to red.
* Adds further tests.

accessrequests: module improvements

---

zenodo/config.py
zenodo/modules/grants/tasks.py
zenodo/modules/quotas/__init__.py
zenodo/modules/quotas/admin.py
zenodo/modules/quotas/config.py
zenodo/modules/quotas/metrics/__init__.py
zenodo/modules/quotas/metrics/afs.py
zenodo/modules/quotas/metrics/deposit.py
zenodo/modules/quotas/models.py
zenodo/modules/quotas/registry.py
zenodo/modules/quotas/signals.py
zenodo/modules/quotas/tasks.py

* Adds new module for keeping track of resource usage.

quotas: initial release

---

zenodo/config.py

global: orcid base_url fix

---

zenodo/modules/deposit/fields/license_field.py

* Fixes issue with licenses not being sorted alphabetically.
(closes 302)

deposit: license ordering fix

---

zenodo/base/format_templates/DataCite.xsl
zenodo/base/format_templates/DataCite3.xsl
zenodo/base/format_templates/OAI_DataCite.xsl
zenodo/base/format_templates/OAI_DataCite3.xsl
zenodo/base/recordext/fields/zenodo.cfg
zenodo/base/recordext/functions/resolve_authority.py
zenodo/base/templates/zenodo/api.html
zenodo/base/testsuite/test_jsonext.py
zenodo/modules/deposit/forms.py
zenodo/modules/deposit/testsuite/test_zenodo_api.py

* Adds authors REST API support (addresses #217).

base: authors REST API support

---

zenodo/base/format_elements/bfe_subjects.py
zenodo/base/format_templates/DataCite.xsl
zenodo/base/format_templates/DataCite3.xsl
zenodo/base/format_templates/OAI_DataCite.xsl
zenodo/base/format_templates/OAI_DataCite3.xsl
zenodo/base/recordext/fields/zenodo.cfg
zenodo/base/recordext/functions/resolve_authority.py
zenodo/base/recordext/functions/resolve_subject.py
zenodo/base/templates/format/record/Default_HTML_info.tpl
zenodo/base/templates/zenodo/api.html
zenodo/base/testsuite/test_jsonext.py
zenodo/modules/deposit/forms.py
zenodo/modules/deposit/testsuite/test_zenodo_api.py
zenodo/modules/deposit/workflows/upload.py

* Adds support for subject identifiers REST API. (addresses #217)

base: subject identifiers REST API addition

---

zenodo/base/format_elements/bfe_subjects.py
zenodo/base/format_templates/DataCite.xsl
zenodo/base/format_templates/DataCite3.xsl
zenodo/base/format_templates/OAI_DataCite.xsl
zenodo/base/format_templates/OAI_DataCite3.xsl
zenodo/base/recordext/fields/zenodo.cfg
zenodo/base/recordext/functions/resolve_authority.py
zenodo/base/recordext/functions/resolve_subject.py
zenodo/base/templates/format/record/Default_HTML_detailed.tpl
zenodo/base/templates/format/record/Default_HTML_info.tpl
zenodo/base/templates/zenodo/api.html
zenodo/base/testsuite/test_jsonext.py
zenodo/modules/deposit/forms.py
zenodo/modules/deposit/testsuite/test_zenodo_api.py
zenodo/modules/deposit/workflows/upload.py

* Adds support for contributors (closes #274).

base: support for contributors

---

zenodo/modules/deposit/templates/deposit/index.html

* Adds possibility to specify maximum number of files per upload.

deposit: provide maximum files count per upload

---

zenodo/base/format_templates/DataCite.xsl
zenodo/base/format_templates/DataCite3.xsl
zenodo/base/format_templates/OAI_DataCite.xsl
zenodo/base/format_templates/OAI_DataCite3.xsl
zenodo/base/upgrades/zenodo_2015_06_24_new_type_lessons.py
zenodo/config.py
zenodo/demosite/fixtures/search.py
zenodo/modules/deposit/fields/objecttype_field.py

* Adds new upload type lessons. (closes #314)

deposit: new upload type lessons addition

---

zenodo/modules/deposit/tasks.py

* Change title into unicode string. (closes #316)

deposit: UnicodeEncodeError in notification fix

---

zenodo/modules/deposit/forms.py

* Changed the label for publication type on the upload interface from
"Type of publication" to "Publication Type".
* Resolves #320 
Signed-off-by: otron <oddweb42+gith@gmail.com>

deposit: Harmonizes wording of pub. and img type

---

base.requirements.txt
zenodo/base/views.py
zenodo/modules/citationformatter/views.py
zenodo/modules/deposit/forms.py

* Moves invenio.utils.persistentid to external package IDUtils.

global: idutils externalization

---

zenodo/base/templates/format/record/Default_HTML_info.tpl

* Fixes link generated for subjects.

base: subjects display fix

---

base.requirements.txt
zenodo/base/recordext/fields/zenodo.cfg
zenodo/base/recordext/functions/resolve_authority.py
zenodo/base/recordext/functions/strip_prefix.py
zenodo/base/testsuite/test_jsonext.py
zenodo/modules/deposit/testsuite/test_zenodo_api.py

* Changes GND identifier serialization and handling.

base: gnd identifier serialization change

---

zenodo/base/templates/zenodo/api.html
zenodo/base/views.py
zenodo/modules/deposit/forms.py

* Adds isCompiledBy/Compiles related identifiers relationship types.
(closes #354)

deposit: isCompiledBy/compiles relationship types

---

zenodo/base/tasks.py
zenodo/config.py

* Checks if all DOIs in records have been registered and registers
DOIs which haven't been registered yet.

base: doi consistency check

---

zenodo/base/format_elements/bfe_openaire_meeting.py

* Adds conference link to meeting format element (closes zenodo#381).

base: conference link addition

---

zenodo/base/templates/format/record/Default_HTML_brief.tpl
zenodo/base/templates/format/record/Provisional_HTML_brief.tpl

* Filters out contributors from authors list
(addresses zenodo/zenodo#387).

base: contributors included in authors list fix

---

base.requirements.txt
zenodo/base/metrics/__init__.py
zenodo/modules/quotas/publishers/cern.py

quotas: cernservicexml upgrade

---

zenodo/base/views.py
zenodo/config.py
zenodo/modules/deposit/testsuite/test_zenodo_api.py
zenodo/modules/quotas/metrics/deposit.py

* Adds a DOI redirection that redirects to Zenodo record for a given
DOI if it exists in Zenodo.

base: doi redirect view

---

zenodo/config.py
zenodo/modules/deposit/tasks.py
zenodo/modules/quotas/metrics/filesystem.py

deposit: title encoding fix

---

zenodo/modules/deposit/testsuite/test_zenodo_api.py

* Fixes the problem with request context remaining on stack

deposit: depositions list unit test fix

---

setup.py
zenodo/config.py
zenodo/modules/records/data/objecttypes.json
zenodo/modules/records/models.py
zenodo/modules/records/serializers/schemas/json.py
zenodo/modules/records/templates/zenodo_records/record_export.html
zenodo/modules/records/views.py
zenodo/modules/search_ui/static/templates/zenodo_search_ui/facets.html
zenodo/modules/search_ui/static/templates/zenodo_search_ui/results.html
zenodo/modules/search_ui/templates/zenodo_search_ui/search.html
zenodo/modules/theme/bundles.py
zenodo/modules/theme/static/js/zenodo-build.js
zenodo/modules/theme/static/js/zenodo/filters/module.js
zenodo/modules/theme/static/js/zenodo/filters/safe.js
zenodo/modules/theme/static/js/zenodo/filters/striptags.js
zenodo/modules/theme/static/js/zenodo/filters/titlecase.js
zenodo/modules/theme/static/scss/search.scss
zenodo/modules/theme/templates/zenodo_theme/footer.html
zenodo/modules/theme/templates/zenodo_theme/security/register_user.html

* Adds titlecase angular template filter.
* Fixes missing object types.
* Adds extra fields to JSON serialization.

search_ui: angular filters and serialization

---

AUTHORS.rst
zenodo/modules/fixtures/data/pages/benefits.html
zenodo/modules/fixtures/data/pages/features.html
zenodo/modules/frontpage/templates/zenodo_frontpage/benefits.html

* Adjusts a phrase on the frontpage, benefits and features pages.
(closes #457)

pages: text adjustment

---

setup.py
tests/unit/conftest.py
tests/unit/records/test_bibtex_serializer.py
zenodo/config.py
zenodo/factory.py
zenodo/modules/records/serializers/__init__.py
zenodo/modules/records/serializers/bibtex.py

* Adds a bibtex serializer. (closes #484)

records: bibtex serializer addition

---

.travis.yml
zenodo/config.py
zenodo/factory.py
zenodo/modules/fixtures/data/pages.json
zenodo/modules/fixtures/data/pages/features.html
zenodo/modules/theme/static/scss/pages.scss
zenodo/modules/theme/static/scss/styles.scss
zenodo/modules/theme/static/scss/variables.scss
zenodo/modules/theme/templates/zenodo_theme/full_page.html
zenodo/modules/theme/templates/zenodo_theme/page.html

* Improves graphically the features page. (closes #417)
* Fixes Roboto font loading.

fixtures: features page cosmetic improvements

---

setup.py
tests/unit/conftest.py
tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_dc.py
zenodo/modules/records/data/objecttypes.json
zenodo/modules/records/jsonschemas/records/objecttype-v1.0.0.json
zenodo/modules/records/serializers/schemas/datacite.py
zenodo/modules/records/serializers/schemas/dc.py

* Adds Dublin Core mapping according to OpenAIRE Guidelines.
(closes #416) (closes #415) (addresses #441)

records: dublin core mapping

---

setup.py
zenodo/modules/records/indexer.py
zenodo/modules/records/serializers/to_marc21/__init__.py
zenodo/modules/records/serializers/to_marc21/rules.py

records: initial marcxml mapping

---

AUTHORS.rst
tests/unit/records/test_bibtex_serializer.py
zenodo/modules/records/serializers/bibtex.py

* Adds bibtex testsuites. (closes #496)

tests: bibtex testsuites addition

---

tests/unit/conftest.py
tests/unit/records/test_grant_linking.py
zenodo/config.py

* Adds simple test case for properly replacing grants reference.
(closes #487)

records: grants jsonref replacement testing

---

tests/unit/conftest.py
zenodo/config.py
zenodo/modules/records/indexer.py

* Fixes receiver after upstream package changed.

records: receiver fix

---

tests/unit/records/test_schemas_marcxml.py
zenodo/modules/records/serializers/schemas/marcxml.py
zenodo/modules/records/serializers/to_marc21/rules.py

* Improves marcxml mappings. (closes #501)

records: marcxml mapping improvement

---

setup.cfg
tests/unit/records/test_schemas_marcxml.py
zenodo/modules/records/serializers/schemas/marcxml.py

* Fixes issue on empty or absent fields. (closes #513)

records: fix marcxml schema serializer

---

tests/unit/records/test_schemas_marcxml.py
zenodo/modules/records/serializers/schemas/marcxml.py

* Fix schema to removes empty tags. (closes #517)

records: fix marcxml generation

---

.travis.yml
INSTALL.rst
docs/installation.rst
requirements.devel.txt
scripts/index.sh
scripts/loadgrants.sh
scripts/recreate.sh
setup.py
tests/unit/conftest.py
tests/unit/records/test_schemas_marcxml.py
zenodo/config.py
zenodo/modules/fixtures/cli.py
zenodo/modules/fixtures/files.py
zenodo/modules/fixtures/grants.py
zenodo/modules/fixtures/oai.py
zenodo/modules/fixtures/pages.py
zenodo/modules/fixtures/records.py
zenodo/modules/fixtures/utils.py
zenodo/modules/records/serializers/__init__.py
zenodo/modules/records/serializers/schemas/marcxml.py
zenodo/modules/records/templates/zenodo_records/box/files.html
zenodo/modules/records/templates/zenodo_records/box/info.html
zenodo/modules/records/templates/zenodo_records/record_detail.html
zenodo/modules/theme/static/scss/record.scss

indexer: fixes

---

zenodo/config.py
zenodo/modules/theme/templates/zenodo_theme/communities/base.html
zenodo/modules/theme/templates/zenodo_theme/javascript.html

global: mathjax support

---

zenodo/modules/deposit/templates/zenodo_deposit/index.html
zenodo/modules/search_ui/templates/zenodo_search_ui/search.html
zenodo/modules/theme/bundles.py
zenodo/modules/theme/static/js/zenodo.js
zenodo/modules/theme/templates/zenodo_theme/communities/base.html
zenodo/modules/theme/templates/zenodo_theme/communities/curate.html
zenodo/modules/theme/templates/zenodo_theme/communities/search.html

global: angular loading bar addition

---

setup.py
zenodo/config.py
zenodo/modules/deposit/fetchers.py
zenodo/modules/deposit/minters.py
zenodo/modules/deposit/providers.py

* Adds a deposit minter, provider and fetcher.

deposit: integer PID values

---

setup.py
tests/unit/records/test_models.py
zenodo/config.py
zenodo/modules/fixtures/data/records.json
zenodo/modules/records/models.py
zenodo/modules/records/permissions.py
zenodo/modules/records/templates/zenodo_records/box/files.html
zenodo/modules/records/templates/zenodo_records/record_detail.html
zenodo/modules/records/views.py

* Lists files in record view only if the viewer has a permission to
view them. (closes #423)

views: file listing based on permissions

---

tests/unit/conftest.py
tests/unit/deposit/test_loaders_legacyjson.py
tests/unit/deposit/test_zenodo_api.py
tests/unit/deposit/test_zenodo_api_quickstart.py
tests/unit/helpers.py
tests/unit/records/test_grant_linking.py
tests/unit/records/test_permissions.py
zenodo/config.py
zenodo/modules/deposit/loaders/schemas/legacyjson.py
zenodo/modules/deposit/query.py
zenodo/modules/fixtures/cli.py
zenodo/modules/fixtures/licenses.py
zenodo/modules/records/serializers/__init__.py
zenodo/modules/records/serializers/legacyjson.py
zenodo/modules/records/views.py

deposit: fix permissions of Deposit REST API

---

setup.py
tests/unit/conftest.py
tests/unit/deposit/test_loaders_legacyjson.py
tests/unit/jsonschemas/test_jsonschemas_compilers.py
tests/unit/jsonschemas/test_utils.py
zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json
zenodo/modules/deposit/jsonschemas/deposits/records/record_src-v1.0.0.json
zenodo/modules/deposit/loaders/schemas/legacyjson.py
zenodo/modules/jsonschemas/__init__.py
zenodo/modules/jsonschemas/cli.py
zenodo/modules/jsonschemas/compilers.py
zenodo/modules/jsonschemas/config.py
zenodo/modules/jsonschemas/ext.py
zenodo/modules/jsonschemas/utils.py
zenodo/modules/records/jsonschemas/records/base-v1.0.0.json
zenodo/modules/records/jsonschemas/records/file-v1.0.0.json
zenodo/modules/records/jsonschemas/records/file_src-v1.0.0.json
zenodo/modules/records/jsonschemas/records/record-v1.0.0.json
zenodo/modules/records/jsonschemas/records/record_src-v1.0.0.json

* Adds ZenodoJSONSchemas module for JSON schema compilation.
* Adds first version of compiled JSON schemas for record and deposit.
Closes #575

global: zenodo-jsonschemas module

---

tests/unit/deposit/test_zenodo_api_quickstart.py
tests/unit/records/test_schemas_legacyjson.py
zenodo/modules/records/serializers/schemas/legacyjson.py

* Fixes legacy schema fields. (closes #570)

deposit: fix legacy schema fields

---

docs/conf.py
setup.py

* Pins the flask version to 0.10.1

setup: pin flask 0.10.1

---

docs/conf.py
setup.py
tests/unit/conftest.py
tests/unit/deposit/test_loaders_legacyjson.py
zenodo/config.py
zenodo/modules/deposit/api.py

* Adds custom  Zenodo API for deposit.

global: zenodo deposit api

---

Dockerfile
INSTALL.rst
docker-compose.yml
docker/docker-entrypoint.sh
docker/es/Dockerfile
docker/nginx/Dockerfile
docker/nginx/conf.d/default.conf
docker/statsd/Dockerfile
docker/statsd/config.js
docker/statsd/init-es.sh
docker/statsd/init.sh
docs/conf.py
docs/installation.rst
requirements.devel.txt
scripts/index.sh
scripts/init.sh
scripts/recreate.sh
scripts/setup-assets.sh
scripts/setup-npm.sh
setup.py
zenodo/__init__.py
zenodo/config.py
zenodo/factory.py

* Adds basic request timing via statsd.
* Adds statsd setup to docker configuration.

global: statsd support

---

zenodo/modules/deposit/mappings/deposits/records/record-v1.0.0.json

* Changed desposit mapping name.

deposit: mapping name change

---

requirements.devel.txt
tests/unit/conftest.py
tests/unit/deposit/test_communities_merging.py
zenodo/modules/deposit/api.py

* Adds communities merging for deposit.

deposit: communities merging

---

base.requirements.txt
zenodo/modules/github/utils.py
zenodo/modules/github/views/handlers.py

* Fixes issue with GitHub login which stopped working due to GitHub
changing the way access token as generated.

github: login fix

---

tests/unit/conftest.py
tests/unit/deposit/test_communities_merging.py
zenodo/modules/deposit/api.py

* Adds automatic accepting of communites owned by any of deposit owners.

deposit: automatic accepting of owned communities

---

setup.py
tests/unit/conftest.py
tests/unit/deposit/test_communities_merging.py
tests/unit/deposit/test_sips.py
zenodo/config.py
zenodo/modules/deposit/api.py
zenodo/modules/sipstore/__init__.py
zenodo/modules/sipstore/api.py
zenodo/modules/sipstore/jsonschemas/__init__.py
zenodo/modules/sipstore/jsonschemas/sipstore/agent-webclient-v1.0.0.json

* Adds SIP creation for deposit publishing

deposit: addition of sip creation

---

zenodo/modules/theme/static/scss/cover.scss
zenodo/modules/theme/templates/zenodo_theme/page_cover.html

* Adds flashed messages to the cover page. (closes #606)

ui: add message flashing to cover page

---

zenodo/modules/deposit/static/templates/zenodo_deposit/results.html
zenodo/modules/records/serializers/schemas/json.py

deposit: json serialization for empty deposit fix

---

zenodo/modules/records/templates/zenodo_records/box/preview.html

records: preview fix

---

tests/unit/records/test_schemas_csl.py
zenodo/modules/records/serializers/schemas/csl.py

records: minor updates to csl serialization

---

requirements.devel.txt
scripts/upload.py
setup.py
zenodo/config.py
zenodo/modules/deposit/api.py
zenodo/modules/records/permissions.py
zenodo/modules/records/templates/zenodo_records/box/files.html

records: accessrequests permission check

---

scripts/recreate.sh
tests/unit/redirector/test_redirection.py
zenodo/modules/theme/bundles.py
zenodo/modules/theme/static/js/zenodo-settings.js
zenodo/modules/theme/static/js/zenodo.js

* Adds clipboard script. (closes zenodo/zenodo-accessrequests#5)

theme: clipboard script addition

---

Dockerfile
docker-compose.yml

docker: fix installation

---

zenodo/config.py
zenodo/modules/records/static/templates/invenio_csl/item.html
zenodo/modules/records/templates/zenodo_records/box/references.html
zenodo/modules/records/templates/zenodo_records/box/share.html
zenodo/modules/records/templates/zenodo_records/record_detail.html
zenodo/modules/theme/bundles.py

* Adds references display in record details view. (closes #656)

records-ui: display references

---

requirements.txt

* Unpins migrationkit from a specific commit.

setup: migrationkit unpinning

---

.editorconfig
run-tests.sh
tests/unit/deposit/test_api_editflow.py
tests/unit/github/test_api.py
tests/unit/records/test_schemas_legacyjson_load.py
zenodo/modules/deposit/ext.py
zenodo/modules/fixtures/cli.py
zenodo/modules/fixtures/communities.py
zenodo/modules/github/api.py
zenodo/modules/records/minters.py

global: import sort fixes

---

requirements.txt
zenodo/config.py

global: dependency name update after migrationkit refactoring

---

docker/haproxy/haproxy.cfg
docker/nginx/conf.d/default.conf

* Improves HAProxy configuration.

docker: haproxy conf improvement

---

zenodo/config.py
zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html
zenodo/modules/deposit/static/templates/zenodo_deposit/array.html
zenodo/modules/deposit/static/templates/zenodo_deposit/button.html
zenodo/modules/deposit/static/templates/zenodo_deposit/ckeditor.html
zenodo/modules/deposit/static/templates/zenodo_deposit/datepicker.html
zenodo/modules/deposit/static/templates/zenodo_deposit/default.html
zenodo/modules/deposit/static/templates/zenodo_deposit/fieldset.html
zenodo/modules/deposit/static/templates/zenodo_deposit/form.html
zenodo/modules/deposit/static/templates/zenodo_deposit/radios.html
zenodo/modules/deposit/static/templates/zenodo_deposit/radios_inline.html
zenodo/modules/deposit/static/templates/zenodo_deposit/select.html
zenodo/modules/deposit/static/templates/zenodo_deposit/textarea.html
zenodo/modules/deposit/static/templates/zenodo_deposit/uiselect.html
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/records/ext.py
zenodo/modules/records/serializers/schemas/legacyjson.py
zenodo/modules/records/utils.py
zenodo/modules/theme/bundles.py
zenodo/modules/theme/static/scss/deposit.scss

* Configures autocomplete fields to their API endpoints and passes
the necessary url parameters. (addresses #671)
* Adds custom templates for various field types.
* Adds datepicker form field type for dates.
* Adds ckeditor form field type.
* Adds ui-sortable for array fields that need ordering.
* Uses legacy record jsonschema for form validation.
* Adds app wide record serializer template filter.

deposit: enhanced form fields and legacy schema

---

zenodo/factory.py
zenodo/modules/deposit/errors.py
zenodo/modules/deposit/indexer.py
zenodo/modules/deposit/mappings/deposits/records/record-v1.0.0.json

* Adds errors dictionary to MarshmallowErrors string representation.
* Fixes indexing of date field in Deposit grant information.

validation: verbose marshmallow errors exception

---

requirements.txt
tests/unit/conftest.py
tests/unit/deposit/test_api_files.py
tests/unit/deposit/test_api_metadata.py
tests/unit/github/test_api.py
tests/unit/records/test_schemas_legacyjson_load.py
zenodo/config.py
zenodo/modules/deposit/api.py
zenodo/modules/deposit/errors.py
zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html
zenodo/modules/deposit/static/templates/zenodo_deposit/alert.html
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/deposit/views.py

(closes #699) (closes #698) (closes #716)  (closes #719)

deposit: form and api fixes

---

tests/unit/deposit/test_deposit_views.py
zenodo/config.py
zenodo/modules/deposit/fetchers.py
zenodo/modules/deposit/views.py
zenodo/modules/records/permissions.py

* Fixes issue with edit view not being protected.
* Adds tests for checking deposit and record URLs.
(closes #715)

deposit: edit view login required fix

---

zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/deposit/views.py

* Adds current date (according to UTC) as default publication date.
(closes #714)

deposit: publication date default

---

requirements.txt
tests/unit/records/test_schemas_legacyjson_load.py
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/deposit/static/templates/zenodo_deposit/alert.html
zenodo/modules/deposit/static/templates/zenodo_deposit/prereserve_doi.html
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/records/serializers/__init__.py
zenodo/modules/records/serializers/fields/doi.py
zenodo/modules/records/serializers/schemas/csl.py
zenodo/modules/records/serializers/schemas/json.py
zenodo/modules/records/serializers/schemas/legacyjson.py
zenodo/modules/records/templates/zenodo_records/record_detail.html

deposit: doi validation error fix + other fixes

---

zenodo/config.py
zenodo/modules/records/templates/zenodo_records/box/info.html
zenodo/modules/records/templates/zenodo_records/macros/authors.html
zenodo/modules/records/templates/zenodo_records/record_detail.html
zenodo/modules/records/views.py

* Adds missing metadata from template. (closes #724)

records: detail template missing metadata fix

---

zenodo/modules/deposit/mappings/deposits/records/record-v1.0.0.json
zenodo/modules/records/mappings/records/record-v1.0.0.json

* Updates Elasticsearch mappings to match JSONSchemas for record and
deposit.

search: elasticsearch mappings update

---

zenodo/modules/deposit/static/templates/zenodo_deposit/alert.html

deposit: fix second alert display

---

scripts/setup-npm.sh
zenodo/config.py
zenodo/modules/deposit/config.py
zenodo/modules/deposit/static/templates/zenodo_deposit/results.html
zenodo/modules/records/serializers/schemas/json.py

global: pinned npm packages versions

---

zenodo/modules/records/serializers/schemas/json.py

deposit: recid fix for deposit ui marshmallow schema

---

zenodo/config.py
zenodo/modules/theme/collect.py

* Adds filter to remove the Flask application's static folder.

theme: collect filter

---

zenodo/config.py
zenodo/modules/theme/collect.py

theme: collect filter fix

---

zenodo/config.py

config: secure session cookie

---

zenodo/modules/deposit/static/templates/zenodo_deposit/alert.html

* Populates the preserved_doi field on initial form save.

deposit: prereserved_doi field population

---

requirements.txt
setup.py
zenodo/modules/frontpage/templates/zenodo_frontpage/index.html

frontpage: missing div tag

---

zenodo/modules/fixtures/data/pages/about.html
zenodo/modules/fixtures/data/pages/faq.html
zenodo/modules/fixtures/data/pages/features.html
zenodo/modules/frontpage/templates/zenodo_frontpage/benefits.html
zenodo/modules/frontpage/templates/zenodo_frontpage/index.html

fixtures: pages update

---

tests/unit/github/test_api.py
zenodo/modules/github/api.py

* Sends the Datacite registration task after a GitHub release.

github: send datacite registration task

---

setup.py

setup: xrootdpyfs version bump

---

requirements.xrootd.txt

installation: xrootdpyfs v0.1.3

---

zenodo/modules/records/serializers/schemas/csl.py

citeproc: clean pages field

---

requirements.txt
zenodo/modules/deposit/loaders/base.py
zenodo/modules/records/serializers/schemas/common.py

setup: updated zenodo-migrator dependency

---

tests/unit/deposit/test_communities_merging.py
tests/unit/github/test_api.py
zenodo/modules/deposit/api.py
zenodo/modules/github/api.py
zenodo/modules/records/serializers/schemas/csl.py
zenodo/modules/utils/__init__.py
zenodo/modules/utils/cli.py

utils: addition of datacite registration CLI

---

zenodo/config.py
zenodo/modules/records/views.py

* Sorts files by filename when selecting the default preview file in
records view. (closes #811)

ui: preview file selection

---

tests/unit/deposit/test_minters.py
zenodo/config.py

config: oai server id prefix

---

tests/unit/conftest.py
tests/unit/records/test_schemas_marcxml.py
zenodo/modules/records/api.py
zenodo/modules/records/serializers/schemas/marc21.py
zenodo/modules/records/serializers/to_marc21/rules.py
zenodo/modules/utils/cli.py

marc21: addition of marc21 rule for conference URL

---

zenodo/modules/utils/cli.py

global: file upload CLI bugfixes

---

zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html

deposit-ui: mouse-over descriptions for Save, Publish and Delete buttons

---

zenodo/modules/fixtures/data/pages/api.html

replace field 'id' by 'identifier' in json example of subjects

fix issue #865

---

MANIFEST.in
README.rst
docs/requirements.txt
zenodo/__init__.py
zenodo/config.py
zenodo/modules/deposit/tasks.py

docs: move to readthedocs.io

---

zenodo/modules/redirector/config.py
zenodo/modules/redirector/views.py
zenodo/modules/theme/templates/zenodo_theme/footer.html

Signed-off-by: Krzysztof Nowak k.nowak@cern.ch

views: redirection endpoint for donation page

---

docker/nginx/nginx.conf
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/deposit/static/templates/zenodo_deposit/alert.html
zenodo/modules/deposit/static/templates/zenodo_deposit/list.html
zenodo/modules/deposit/static/templates/zenodo_deposit/prereserve_doi.html
zenodo/modules/deposit/static/templates/zenodo_deposit/results.html
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/deposit/templates/zenodo_deposit/index.html
zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
zenodo/modules/records/models.py
zenodo/modules/redirector/config.py
zenodo/modules/redirector/views.py
zenodo/modules/search_ui/static/templates/zenodo_search_ui/results.html
zenodo/modules/search_ui/static/templates/zenodo_search_ui/results_curate.html
zenodo/modules/search_ui/templates/zenodo_search_ui/search.html
zenodo/modules/theme/bundles.py
zenodo/modules/theme/static/js/zenodo.search.js
zenodo/modules/theme/static/scss/deposit.scss
zenodo/modules/theme/templates/zenodo_theme/communities/base.html
zenodo/modules/theme/templates/zenodo_theme/communities/curate.html
zenodo/modules/theme/templates/zenodo_theme/communities/search.html
zenodo/modules/theme/templates/zenodo_theme/footer.html

- Updates nginx's gzip configuration with more mimetypes.
Signed-off-by: Alexander Ioannidis a.ioannidis@cern.ch

nginx: additional gzip mimetypes

---

zenodo/modules/deposit/templates/zenodo_deposit/edit.html

* Fix bug on deposit pre-reserve DOI for already created deposit.

deposit-ui: bug fix for pre-reserve DOI

---

zenodo/modules/utils/cli.py
zenodo/modules/utils/tasks.py

utils: addition of files metadata repair CLI

---

tests/unit/conftest.py
tests/unit/deposit/test_communities_merging.py
zenodo/modules/deposit/api.py
zenodo/modules/deposit/config.py
zenodo/modules/fixtures/cli.py
zenodo/modules/jsonschemas/cli.py
zenodo/modules/utils/cli.py
zenodo/modules/utils/tasks.py

Signed-off-by: Krzysztof Nowak k.nowak@cern.ch

deposit: auto-requesting grant communities

---

tests/unit/conftest.py
tests/unit/github/test_github_cli.py
zenodo/cli.py
zenodo/modules/github/cli.py
zenodo/modules/utils/cli.py

github: addition of github CLI

---

tests/unit/github/test_github_cli.py
zenodo/modules/github/cli.py

github: github CLI fix

---

tests/unit/github/test_github_cli.py
zenodo/modules/github/api.py
zenodo/modules/github/cli.py

github: removal of transfer command from CLI

---

setup.py
tests/unit/auditor/test_oai.py
tests/unit/auditor/test_records.py
tests/unit/conftest.py
tests/unit/records/test_schemas_marcxml.py
zenodo/modules/auditor/__init__.py
zenodo/modules/auditor/api.py
zenodo/modules/auditor/cli.py
zenodo/modules/auditor/ext.py
zenodo/modules/auditor/oai.py
zenodo/modules/auditor/records.py
zenodo/modules/auditor/tasks.py
zenodo/modules/auditor/utils.py

* Adds the ZenodoAuditor module, responsible for auditing record,
file and served content consistency.

auditor: initial commit

---

requirements.txt
setup.py

installation: zenodo-accessrequests version bump

---

zenodo/modules/fixtures/data/licenses.json
zenodo/modules/fixtures/licenses.py

fixtures: addition of a free to read license

---

zenodo/config.py
zenodo/modules/records/minters.py
zenodo/modules/utils/tasks.py

records: oaiid_minter refactoring

---

tests/unit/conftest.py
tests/unit/utils/test_oai_update.py
zenodo/config.py
zenodo/modules/auditor/oai.py
zenodo/modules/records/jsonschemas/records/file_src-v1.0.0.json
zenodo/modules/records/jsonschemas/records/records-files-v1.0.0.json
zenodo/modules/records/mappings/records/records-files-v1.0.0.json
zenodo/modules/utils/cli.py
zenodo/modules/utils/tasks.py

utils: search pattern oaisets updates

---

zenodo/modules/utils/tasks.py

utils: record indexing fix

---

requirements.xrootd.txt
setup.py

* Fixes issue with fixity checks from AFS.

installation: invenio-xrootd version bump

---

README.rst

I have visited your page and found that:
1. Readme.rst : Add link to Install.rst 
>>> [Install.rst](https://github.com/zenodo/zenodo/blob/master/INSTALL.rst)
2. Readme.rst : Add gitter badge
>>> Added [![Join the chat at https://gitter.im/zenodo/zenodo](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/zenodo/zenodo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
3. Readme.rst : Correct invenio link
>>> [Invenio](http://github.com/inveniosoftware/invenio)
These are some improvement according to me.

Updated Readme.rst

---

zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
zenodo/modules/redirector/config.py
zenodo/modules/redirector/views.py
zenodo/modules/theme/templates/zenodo_theme/footer.html

template: footer update with user docs links

---

zenodo/modules/frontpage/templates/zenodo_frontpage/index.html

frontpage: blog url bugfix on frontpage infobox

---

CONTRIBUTING.rst
docs/development/guide.rst
docs/development/process.rst
zenodo/modules/records/serializers/schemas/datacite.py

Suggested Improvement in rst files.
* Typo Fix in CONTRIBUTING.rst
* Added Link to guide.rst and process.rst

docs: typo and link

---

zenodo/modules/records/serializers/bibtex.py

records: typo fix

---

setup.py
zenodo/modules/pages/__init__.py
zenodo/modules/pages/config.py
zenodo/modules/pages/ext.py
zenodo/modules/pages/forms.py
zenodo/modules/pages/templates/zenodo_pages/contact_form.html
zenodo/modules/pages/templates/zenodo_pages/email_body.html
zenodo/modules/pages/templates/zenodo_pages/email_title.html
zenodo/modules/pages/utils.py
zenodo/modules/pages/views.py
zenodo/modules/redirector/config.py

* Form is added for contact.
* Contact form automatically detects OS and browser.
* Sends information in the form of email notification.
Enhancement for #901.

global: contact form

---

tests/unit/records/test_bibtex_serializer.py
zenodo/modules/records/serializers/bibtex.py

The coverage checking seems to be failing due to the bug discussed in (https://github.com/zenodo/zenodo/issues/1027).

records: Add venue to bibtex as discussed in #855

---

scripts/index.sh

* Fixes issue with reindexing not taking deleted records into account.
(closes #1016)

scripts: reindexing fix

---

zenodo/modules/records/serializers/schemas/common.py
zenodo/modules/records/templates/zenodo_records/box/info.html

record-ui: addition of permission check for Concept DOI button

---

docker/es/Dockerfile

docker: fix ElasticHQ installation issue

---

zenodo/modules/records/templates/zenodo_records/record_detail.html

records: detail template updates

---

INSTALL.rst

Signed-off-by: Aman Jain <jainaman224@gmail.com>

docs: typo fix

---

README.rst
docs/license.rst

* Updated License term from 2009-2016 to 2009-2017.
Signed-off-by: Aman Jain <jainaman224@gmail.com>

LICENSE: updated term

---

tests/unit/github/test_api.py
zenodo/modules/deposit/api.py
zenodo/modules/deposit/loaders/base.py
zenodo/modules/github/api.py

deposit: disallow custom DOI for versioned records

---

tests/unit/deposit/test_api_simpleflow.py
zenodo/modules/deposit/api.py
zenodo/modules/deposit/indexer.py
zenodo/modules/records/permissions.py
zenodo/modules/records/templates/zenodo_records/box/versions.html

deposit: fix error response code

---

zenodo/modules/github/api.py

* Automatically upgrades a non-versioned GitHub records to versioning
on new releases.

versioning: GitHub non-versioned releases upgrades

---

zenodo/modules/deposit/views.py

ui: fixes admin record delete view

---

zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
zenodo/modules/records/templates/zenodo_records/box/versions.html

global: add frontpage and record versioning links

---

zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
zenodo/modules/records/templates/zenodo_records/box/versions.html

'master' merge into 'qa'

---

tests/unit/communities/test_communities_api.py
tests/unit/deposit/test_deposit_index.py
tests/unit/deposit/test_deposit_views.py
tests/unit/records/test_records_relations_serialization.py
zenodo/modules/deposit/utils.py
zenodo/modules/deposit/views.py

records-ui: refactoring and fixes for the record deletion

---

zenodo/modules/records/serializers/schemas/common.py
zenodo/modules/records/templates/zenodo_records/box/publishedin.html

* Fixes issue with serializer only working in request context
causing problems with DOI registrations are run in Celery.

records: datacite serializer fix

---

zenodo/modules/deposit/extractor.py
zenodo/modules/deposit/static/templates/zenodo_deposit/list.html
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/deposit/views.py

For now, the title can be updated as the filename after clicking the extracting button.

deposit-ui: mockup button for "extraction" of a metadata

---

zenodo/modules/spam/views.py

spam: spam removal view fixes

---

zenodo/modules/deposit/api.py

deposit: pre-publishing files storage check

---

zenodo/modules/utils/cli.py

utils: file attaching utility

---

zenodo/modules/deposit/templates/zenodo_deposit/edit.html

Signed-off-by: Xiao Meng <xiaom.cs@gmail.com>

metadata-extractor: update the files-processor endpoint

---

tests/unit/pages/test_pages_views.py
zenodo/modules/pages/config.py
zenodo/modules/pages/utils.py
zenodo/modules/pages/views.py

ui: text and fixes for contact form

---

tests/unit/pages/test_pages_views.py
zenodo/modules/pages/config.py
zenodo/modules/pages/utils.py

pages: support confirmation email signature fix

---

tests/unit/pages/test_pages_views.py
zenodo/config.py
zenodo/modules/pages/config.py

accounts: celerybeat schedule for session cleaning

---

zenodo/modules/deposit/views.py

deposit-ui: fixed 404 error for new drafted deposits

---

zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json

deposit: add alternate identifier to schema

---

INSTALL.rst
scripts/init.sh
scripts/loadgrants.sh
scripts/recreate.sh
tests/unit/fixtures/test_fixtures_cli.py
zenodo/modules/fixtures/cli.py
zenodo/modules/fixtures/data/funders.json
zenodo/modules/fixtures/grants.py

* Adds a fixutre containing only the supported funders.

openaire: addition of a fixed funder list

---

zenodo/modules/deposit/static/templates/zenodo_deposit/prereserve_doi.html

deposit-ui: changed DOI reservation label and description

---

tests/unit/records/test_schemas_openaire_json.py
zenodo/modules/openaire/schema.py

openaire: grant link unicode fix

---

tests/unit/communities/test_communities_api.py
tests/unit/conftest.py
zenodo/modules/communities/config.py
zenodo/modules/deposit/api.py

communities: email notification config

---

INSTALL.rst

docs: installation guide with NVM

---

zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json

deposit-ui: wellcome trust funder country fix

---

zenodo/modules/records/data/objecttypes.json

openaire: serialization of the other type

---

tests/unit/records/test_schemas_marcxml.py
zenodo/modules/records/serializers/schemas/marc21.py
zenodo/modules/records/serializers/to_marc21/rules.py

records: marcxml language serialization

---

zenodo/modules/records/templates/zenodo_records/meta.html

* Fixes the serialization of author names in Highwire
meta tags.

record-ui: HTML Highwire meta author name

---

zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/deposit/static/templates/zenodo_deposit/list.html

deposit-ui: opening links on deposit page in new tab

---

tests/unit/helpers.py
tests/unit/support/test_support_views.py
zenodo/modules/support/forms.py
zenodo/modules/support/proxies.py
zenodo/modules/support/templates/zenodo_support/contact_form.html
zenodo/modules/support/utils.py
zenodo/modules/support/views.py

Support form client-side validation

---

zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json

deposit: extended funders form choices

---

zenodo/modules/deposit/minters.py

deposit: fixes an issue with pid value type

---

zenodo/__init__.py
zenodo/config.py

docs: config filename fix

---

scripts/recreate.sh
tests/unit/conftest.py
tests/unit/deposit/test_tasks.py
tests/unit/openaire/test_openaire.py
tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_dc.py
zenodo/config.py
zenodo/modules/communities/api.py
zenodo/modules/communities/views.py
zenodo/modules/deposit/api.py
zenodo/modules/deposit/static/js/zenodo_deposit/directives.js
zenodo/modules/deposit/static/js/zenodo_deposit/filters.js
zenodo/modules/deposit/static/js/zenodo_deposit/providers.js
zenodo/modules/deposit/static/templates/zenodo_deposit/communities.html
zenodo/modules/deposit/static/templates/zenodo_deposit/openaire-subtype.html
zenodo/modules/deposit/tasks.py
zenodo/modules/deposit/templates/zenodo_deposit/edit.html
zenodo/modules/deposit/views.py
zenodo/modules/openaire/config.py
zenodo/modules/openaire/ext.py
zenodo/modules/records/models.py
zenodo/modules/records/serializers/schemas/datacite.py
zenodo/modules/records/serializers/schemas/dc.py
zenodo/modules/records/serializers/schemas/legacyjson.py
zenodo/modules/records/utils.py
zenodo/modules/support/config.py

global: refactoring of OpenAIRE communities configuration

---

tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/records/serializers/schemas/schemaorg.py

records: schemaorg dataset serializer hostname fix

---

tests/unit/sitemap/test_sitemap_views.py
zenodo/modules/sitemap/views.py

sitemap: fixed the sitemap response type to text/xml

---

tests/unit/sitemap/test_sitemap_generator.py
zenodo/modules/sitemap/ext.py

sitemap: removed timeout from sitemap cache

---

tests/unit/sitemap/test_sitemap_generator.py
zenodo/modules/sitemap/generators.py

sitemap date format fix

---

tests/unit/sitemap/test_sitemap_generator.py
zenodo/modules/sitemap/generators.py

sitemap: timestamp formatter fix

---

zenodo/modules/records/templates/zenodo_records/box/curate.html
zenodo/modules/records/views.py
zenodo/modules/search_ui/static/templates/zenodo_search_ui/results_curate.html
zenodo/modules/theme/static/js/zenodo/functions.js

records: show communities in alphabetical order

---

zenodo/modules/records/serializers/schemas/json.py

global: adds files to JSON serializer based on permissions

---

tests/unit/records/test_records_tasks.py
tests/unit/sitemap/test_sitemap_generator.py
zenodo/modules/records/tasks.py
zenodo/modules/sitemap/ext.py

global: set ttl=-1 when calling current_chache.set

---

zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
zenodo/modules/records/templates/zenodo_records/box/record_stats.html

frontpage: add new banner to the sidebar

---

tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_dc.py
zenodo/config.py
zenodo/modules/openaire/helpers.py
zenodo/modules/records/serializers/schemas/datacite.py
zenodo/modules/records/serializers/schemas/dc.py

schemas: change identifier for foreign DOIs

---

requirements.txt
setup.py
tests/unit/stats/test_stats_exporters.py
zenodo/modules/stats/cli.py
zenodo/modules/stats/config.py
zenodo/modules/stats/errors.py
zenodo/modules/stats/exporters.py
zenodo/modules/stats/ext.py
zenodo/modules/stats/tasks.py
zenodo/modules/stats/utils.py

stats: add PiwikExporter

---

zenodo/modules/deposit/static/templates/zenodo_deposit/communities.html
zenodo/modules/theme/static/scss/deposit.scss

* move community logo
* display openaire community name
* addresses #1523

deposit: improve communities search box

---

zenodo/modules/utils/cli.py
zenodo/modules/utils/openaire.py

utils: cli command to update communities mapping

---

zenodo/config.py
zenodo/modules/stats/config.py
zenodo/modules/stats/tasks.py

stats: celery beat schedule for export_stats task

---

docker-compose.full.yml
docker-compose.yml
docker-services.yml
docker/kibana/Dockerfile

docker: kibana image

---

tests/unit/auditor/test_oai.py
tests/unit/conftest.py
zenodo/modules/auditor/oai.py
zenodo/modules/openaire/tasks.py

auditor: oai_id fix and minor refactoring

---

zenodo/modules/support/config.py
zenodo/modules/support/templates/zenodo_support/contact_form.html

If the user asks for a file modification and doesn't attach any files, the following modal will be displayed:

Support: better handling for file upload

---

tests/unit/conftest.py
tests/unit/records/test_serializers_json.py
zenodo/modules/records/serializers/json.py

records: fix closed access record serialization

---

zenodo/modules/records/config.py
zenodo/modules/records/static/templates/citations/facets.html
zenodo/modules/records/static/templates/citations/pagination.html
zenodo/modules/records/static/templates/citations/results.html
zenodo/modules/records/static/templates/citations/selectbox.html
zenodo/modules/records/templates/zenodo_records/box/citations.html
zenodo/modules/records/templates/zenodo_records/record_detail.html
zenodo/modules/theme/static/js/zenodo/filters/citations.js
zenodo/modules/theme/static/js/zenodo/filters/module.js
zenodo/modules/theme/static/scss/record.scss

records: citation box

---

zenodo/modules/records/static/templates/citations/facets.html
zenodo/modules/theme/static/scss/record.scss

records-ui: fix citation filter labels

---

zenodo/modules/theme/static/scss/deposit.scss

deposit-ui: fix community logo overflow

---

tests/unit/records/test_bibtex_serializer.py
zenodo/modules/records/serializers/bibtex.py
zenodo/modules/theme/templates/zenodo_theme/javascript.html

* Fix the case of values with trailing whitespace causing
repetition of the value. (closes #1598)

record-ui: fix bibtex long value formatting

---

zenodo/modules/deposit/static/js/zenodo_deposit/config.js
zenodo/modules/deposit/templates/zenodo_deposit/edit.html

deposit: fix double curly brackets bug

---

tests/unit/openaire/test_openaire_helpers.py
tests/unit/records/test_schemas_openaire_json.py
zenodo/config.py
zenodo/modules/openaire/helpers.py
zenodo/modules/openaire/schema.py
zenodo/modules/openaire/tasks.py
zenodo/modules/records/data/objecttypes.json

* send data to both OpenAIRE beta and prod (address #1650)
* direct index `software` and `other` records (close #1533)
* send communities information (close #1688)
* change portal URL (close #1639)

openaire: update direct indexing

---

tests/unit/conftest.py
tests/unit/openaire/test_openaire.py
zenodo/modules/deposit/static/js/zenodo_deposit/directives.js
zenodo/modules/deposit/static/js/zenodo_deposit/filters.js
zenodo/modules/deposit/static/templates/zenodo_deposit/communities.html
zenodo/modules/openaire/ext.py
zenodo/modules/openaire/helpers.py

openaire: change inverse community mapping

---

zenodo/modules/records/templates/zenodo_records/box/citations.html

records-ui: remove citation box if no doi field

---

tests/unit/deposit/test_api_editflow.py
zenodo/modules/deposit/static/templates/zenodo_deposit/neweversionmodal.html
zenodo/modules/records/serializers/schemas/common.py

* Fixes redirect link for ui  provided by the api
when creating a new version (closes #1622).

deposit-ui: fix redirect link generated

---

zenodo/modules/records/views.py

* Fixes removal button not rendering for
community owners. (closes #1731)

record-ui: fixes removal button not rendering

---

tests/unit/conftest.py
tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_dc.py
tests/unit/records/test_schemas_json_load.py
tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json
zenodo/modules/deposit/mappings/deposits/records/record-v1.0.0.json
zenodo/modules/records/jsonschemas/records/base-v1.0.0.json
zenodo/modules/records/jsonschemas/records/record-v1.0.0.json
zenodo/modules/records/mappings/records/record-v1.0.0.json
zenodo/modules/records/serializers/schemas/common.py
zenodo/modules/records/serializers/schemas/datacite.py
zenodo/modules/records/serializers/schemas/dc.py
zenodo/modules/records/serializers/schemas/schemaorg.py

* support temporal metadata in REST APIs (close #1741)
* serializers for temporal metadata (close #1743)
* support temporal search queries (close #1742)

deposit: support temporal metadata in REST APIs

---

tests/unit/conftest.py
tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_dc.py
tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json
zenodo/modules/deposit/mappings/deposits/records/record-v1.0.0.json
zenodo/modules/records/jsonschemas/records/base-v1.0.0.json
zenodo/modules/records/jsonschemas/records/record-v1.0.0.json
zenodo/modules/records/mappings/records/record-v1.0.0.json
zenodo/modules/records/serializers/schemas/common.py
zenodo/modules/records/serializers/schemas/datacite.py
zenodo/modules/records/serializers/schemas/dc.py
zenodo/modules/records/serializers/schemas/schemaorg.py

deposit: support method field in REST API

---

.travis.yml
docker-services.yml
docker/es/Dockerfile
tests/unit/records/test_api_views.py
zenodo/modules/records/facets.py

* check that top-right lat is gt bottom-left lat
* bump es version in travis and docker

search: add checks on lat and long

---

tests/unit/records/test_schemas_dc.py
zenodo/modules/records/serializers/schemas/dc.py

records: fix dc serializer

---

.travis.yml
tests/unit/records/test_schemas_legacyjson_load.py
zenodo/modules/records/serializers/schemas/common.py

serializers: fixes missing cleanup on load

---

tests/unit/exporter/test_exporter_writers.py
zenodo/modules/exporter/config.py
zenodo/modules/exporter/writers.py

The BLR export job configuration is on puppet.

exporter: configuration for BLR exporter

---

zenodo/config.py
zenodo/modules/search_ui/static/templates/zenodo_search_ui/facets.html

records: add aggregation for 'community' field

---

zenodo/modules/records/serializers/schemas/common.py
zenodo/modules/records/templates/zenodo_records/record_detail.html

serializers: allow HTML in 'notes' field

---

setup.py
zenodo/modules/deposit/utils.py

deposit: remove non Zenodo DOIs

---

tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/records/serializers/schemas/schemaorg.py

records: renamed field in jsonld serializer

---

zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json

deposit-form: make restricted access rights required

---

zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json

* Adds "Finlands Akademi" and "European Environment Agency" funders
to the grant selection dropdown.

deposit-ui: add new funder options

---

zenodo/modules/records/templates/zenodo_records/box/citations.html

records-ui: add citations FAQ link + default on

---

zenodo/modules/records/templates/zenodo_records/record_detail.html

Stop loading Altmetric JavaScript from cloudfront.net

---

zenodo/modules/search_ui/static/templates/zenodo_search_ui/results.html
zenodo/modules/theme/static/js/zenodo/filters/journal.js
zenodo/modules/theme/static/js/zenodo/filters/module.js

search-ui: adds journal information in results

---

tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
zenodo/modules/records/data/objecttypes.json
zenodo/modules/redirector/config.py

global: add PhysicalObject resource type

---

zenodo/modules/records/views.py

*Fixes issue with different extensions present in the record

views: fixes record thumbnail view

---

tests/unit/conftest.py
tests/unit/records/test_schemas_datacite.py
tests/unit/records/test_schemas_schemaorg_jsonld.py
zenodo/modules/records/serializers/schemas/schemaorg.py

Fixes @type in related identifiers for JSON-LD

---

zenodo/modules/records/serializers/dcat.py

* Closes #2185.
Co-Authored-By: Ines <inesruud7@gmail.com>

serializers: add "rdf:resource" attribute in downloadURL

---

zenodo/modules/records/templates/zenodo_records/box/edit.html

Closes https://github.com/zenodo/ops/issues/92

admin-dropdown: change "created_by" to "owners"

---

zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html

closes https://github.com/zenodo/zenodo/issues/2127

deposit-ui: introduce warning pop-up for unpublished deposit Delete button

---

setup.py
tests/unit/metrics/conftest.py
tests/unit/metrics/test_metrics_utils.py
tests/unit/metrics/test_metrics_views.py
zenodo/modules/metrics/__init__.py
zenodo/modules/metrics/api.py
zenodo/modules/metrics/config.py
zenodo/modules/metrics/ext.py
zenodo/modules/metrics/proxies.py
zenodo/modules/metrics/utils.py
zenodo/modules/metrics/views.py

openaire: virtual access KPIs submission

---

zenodo/modules/deposit/templates/zenodo_deposit/edit.html

deposit: "admin-menu" and "bucket size editing" added

---

zenodo/modules/deposit/templates/zenodo_deposit/delete.html
zenodo/modules/records/templates/zenodo_records/macros/admin.html
zenodo/modules/spam/templates/zenodo_spam/delete.html
zenodo/modules/theme/views.py

Closes https://github.com/zenodo/ops/issues/86

admin: added multiple features to the admin deletion menus

---

.github/workflows/tests.yml
zenodo/modules/records/serializers/dcat.py

- ci: install libkrb5-dev
- dcat: remove inner text for URLs

Remove URLs from text nodes in DCAT XML export 

---

docker-services.yml
requirements.txt

- docker: bump PostgreSQL to v12
- installation: bump uWSGI

Bump PostgreSQL and uWSGI

---

zenodo/modules/records/views.py

views: fix thumbnail extensions list

---

tests/unit/records/test_views.py
zenodo/modules/records/views.py

- records-ui: fix REANA badge for unicode
- records-ui: adds "name" parameter tp REANA badges

REANA badge fixes

---

zenodo/config.py
zenodo/modules/spam/views.py

- spam: fix safelist record search query
- search: sort by safelisted records first

Safelist sorting

---

tests/unit/conftest.py
tests/unit/spam/test_forbiddenlist.py
zenodo/modules/deposit/utils.py
zenodo/modules/spam/config.py
zenodo/modules/spam/ext.py
zenodo/modules/spam/forbiddenlist.py
zenodo/modules/spam/proxies.py

This PR raises from the need to improve the search by domain since the list will grow significantly. The code is extracted from @lnielsen zenodo-stats/users analisys.
**Open questions/actions**
- Should we rename "Blacklist" to "ForbiddenList", since we have "safelist" and not "whitelist"? Open to naming ideas.
- Requires a PR to puppet config to add new domains (will do that once this PR is merged)

spam: add indexed domain forbidden list

---

zenodo/modules/records/templates/zenodo_records/box/versions.html

issue #2224: add record.conceptdoi in cite all versions box

---

Dockerfile
scripts/setup-npm.sh

This script fails because npm is not installed. So let's install npm first.

This is to fix bug https://github.com/zenodo/zenodo/issues/2154. 

---

requirements.txt
tests/unit/conftest.py
zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json
zenodo/modules/records/jsonschemas/records/base-v1.0.0.json
zenodo/modules/records/jsonschemas/records/record-v1.0.0.json

installation: bump idutils

---

requirements.txt
setup.py
zenodo/config.py

- installation: bump zenodo-accessrequests
- installation: remove unused dependencies
- Closes #2267.

Bump zenodo-accessrequests

---

zenodo/modules/records/serializers/schemas/common.py

serializers: fix typo in common.py

---

zenodo/modules/deposit/templates/zenodo_deposit/edit.html

- closes https://github.com/zenodo/zenodo/issues/1968
- closes https://github.com/zenodo/zenodo/issues/2311

upload form: rephrase minimum requirements text

---

zenodo/modules/spam/models.py
zenodo/modules/spam/views.py

Still missing a corner case and testing, but this is shipable.

Safelist filtering fixes

---

zenodo/__init__.py

fix typo in __init__.py

---

zenodo/modules/spam/templates/zenodo_spam/safelist/admin.html
zenodo/modules/spam/views.py

Adds another column with total users domain count in the safelisting panel

spam: add domain count in safelist
