- zenodo/base/static/less/zenodo.less
* Removes margin-top from div#push and reduce its height. (closes #75)
> base: remove whitespace on frontpage

- zenodo/base/utils/bibtex.py
* Fixes `other` and `default` subtypes handling in Bibtex formater.
> base: fix bibtex formatter subtypes handling

- zenodo/modules/deposit/forms.py
* Replaces `Required` with `DataRequired`.
> deposit: removal of deprecated WTForms validator

- zenodo/modules/github/views/badge.py
* Adds support for `style` while generating a badge for
specific DOI. (addresses #87).
> github: activate badge style support for DOI

- zenodo/demosite/fixtures/communities.py
* Prepares old communities fixtures for logo addition. (addresses #112)
Signed-off-by: bouzlibop <bouzlibop@gmail.com>
> global: communities logo addition fixtures changes

- zenodo/modules/github/testsuite/fixtures.py
- zenodo/modules/github/utils.py
* moves from using `users/:username/repos` to `user/repos`
API call to get the list of the users repositories. (closes #86)
* NOTE: List your repositories GitHub API now also includes
repositories owned by organizations which the user
can access.
This functionality will apply to all API consumers
beginning February 24, 2015.
> github: list your repositories GitHub API changes

- zenodo/base/format_elements/bfe_openaire_altmetric.py
- zenodo/base/static/less/zenodo.less
- zenodo/base/templates/format/record/Default_HTML_info.tpl
* Changes altmetric widget to always load, but only show when data is
present.
> base: altmetric improvement

- zenodo/base/utils/bibtex.py
* Uses `strftime` from `invenio.utils.date`
instead of this from Standard Library. (closes #209)
> base: bibtex support for dates < 1900

- zenodo/modules/deposit/forms.py
- zenodo/modules/deposit/workflows/upload.py
* Adds validation to prevent removal of existing doi. (addresses #231)
> deposit: better doi validation in edit form

- zenodo/modules/github/templates/github/helpers.html
* Adds doi link in badge modal dialog. (closes #204)
> github: doi link in badge modal dialog

- zenodo/base/views.py
* Removes duplicated definition. (closes #240)
> base: duplicated github logo fix

- zenodo/base/utils/bibtex.py
* Properly resolves format function for default subtype (closes #247).
> base: failing bibtex export fix

- zenodo/base/utils/bibtex.py
* Fixes inproceedings optional fields definition. (closes #249)
> base: BibTeX KeyError fix

- zenodo/base/testsuite/test_zenodo_bibtex.py
- zenodo/base/utils/bibtex.py
This one is rebased on top of https://github.com/zenodo/zenodo/pull/250
> base: BibTeX formatter DOI requirement removal

- zenodo/base/format_templates/DataCite3.xsl
* Changes single to double quotes in JSON for references in datacite
XML. (closes #271)
> records: json in datacite xml export fix

- zenodo/base/format_templates/DataCite3.xsl
* Removes trailing comma from json in datacite export. (closes #277)
> records: last comma in json in datacite removal

- zenodo/base/utils/bibtex.py
* Adds comma after one-line author field. (closes #286)
> records: bibtex missing comma fix

- zenodo/base/templates/format/record/Default_HTML_BibTeX.tpl
- zenodo/base/templates/format/record/Default_HTML_MARC.tpl
* Adds link back to detail view from export pages. (closes #266)
> records: link from exports to detail view addition

- zenodo/base/templates/format/record/Default_HTML_info.tpl
* Makes sure url schema prefix is not shown. (closes #262)
> records: url prefix in alternate ids deletion

- zenodo/base/upgrades/zenodo_2015_06_02_new_subtype_deliverable_and_milestone.py
- zenodo/config.py
- zenodo/demosite/fixtures/search.py
- zenodo/modules/deposit/forms.py
* Adds `deliverable` and `milestone` subtypes to `Publications`.
(closes #280)
> global: new pub subtypes deliverable and milestone

- base.requirements.txt
- setup.py
- zenodo/base/metrics/__init__.py
- zenodo/base/metrics/communities.py
- zenodo/base/metrics/pidstore.py
- zenodo/config.py
- zenodo/modules/quotas/config.py
- zenodo/modules/quotas/metrics/accounts.py
- zenodo/modules/quotas/metrics/bibsched.py
- zenodo/modules/quotas/models.py
- zenodo/modules/quotas/publishers/__init__.py
- zenodo/modules/quotas/publishers/cern.py
- zenodo/modules/quotas/tasks.py
* Adds support for publishing metrics to CERN XSLS service.
(addresses #49)
* Adds bibsched, accounts, communities and pidstore metrics.
(addresses #141)
> quotas: xsls metrics publisher

- zenodo/base/templates/zenodo/api.html
- zenodo/modules/deposit/testsuite/test_zenodo_api.py
- zenodo/modules/deposit/workflows/upload.py
* Adds API documentation for restricted access mode, as well as
access_conditions field. (#closes 263)
> deposit: api documentation

- zenodo/base/templates/search/collection.html
* Fixes class connected with making types filter shown by default.
> base: show types filter by default fix

- zenodo/base/recordext/fields/zenodo.cfg
- zenodo/base/recordext/functions/contributor_datacite2marc.py
- zenodo/base/recordext/functions/contributor_marc2datacite.py
- zenodo/base/static/less/zenodo.less
- zenodo/base/templates/zenodo/api.html
- zenodo/base/testsuite/test_jsonext.py
- zenodo/config.py
- zenodo/modules/deposit/forms.py
- zenodo/modules/deposit/testsuite/test_zenodo_api.py
- zenodo/modules/deposit/workflows/upload.py
- zenodo/modules/github/templates/github/helpers.html
* Changes exposed contributor types to be DataCite compliant.
* Updates API documentation for contributors.
* Fixes data model loading problem for contributors without
affiliation.
* Fixes problem with lesson not being detected as an upload type
during reading from MARC.
> global: contributor field fixes

- zenodo/modules/deposit/forms.py
- zenodo/modules/deposit/validators.py
* Adds check to see if DOI already exists in Zenodo in order to
prevent bibupload from stopping.
> deposit: existing doi check

- zenodo/base/templates/format/record/Default_HTML_share.tpl
* Uses doi url instead of zenodo record url in addthis toolbox.
> base: doi url in addthis toolbox

- tests/unit/records/test_views.py
- zenodo/modules/records/config.py
- zenodo/modules/records/templates/zenodo_records/box/publishedin.html
- zenodo/modules/records/templates/zenodo_records/record_detail.html
- zenodo/modules/records/views.py
* Adds logos of related identifiers to the records detail view.
(closes #489)
> records-ui: logo for related identifiers

- docs/index.rst
- zenodo/modules/fixtures/data/pages/features.html
- zenodo/modules/fixtures/data/pages/policies.html
- zenodo/modules/records/serializers/data/oai_datacite.xsl
- zenodo/modules/records/serializers/data/oai_datacite3.xsl
- zenodo/modules/theme/templates/zenodo_theme/footer.html
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> global: inveniosoftware.org

- .travis.yml
- requirements.devel.txt
- setup.cfg
- setup.py
- tests/unit/conftest.py
- tests/unit/records/test_models.py
- zenodo/modules/fixtures/data/records.json
- zenodo/modules/records/models.py
- zenodo/modules/records/tasks.py
* Adds a task to change access right of embargoed records after the
embargo date has passed. (closes #488)
Reviewed-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
(closes #506)
> records: expired embargo updater task

- setup.py
- zenodo/config.py
- zenodo/modules/deposit/jsonschemas/__init__.py
- zenodo/modules/deposit/jsonschemas/zenodo_deposit/deposit-v1.0.0.json
- zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
- zenodo/modules/theme/static/scss/styles.scss
* Adds jsonschema for Zenodo deposits form and an angular schema form
definition.
> deposits: deposits form for zenodo

- zenodo/modules/records/templates/zenodo_records/box/info.html
- zenodo/modules/theme/static/scss/record.scss
* Adds alternate identifiers to the records UI info box.
* Fixes spacing issue for alternate identifiers. (closes #490)
* Fixes long keyword linebreaks. (closes #467)
> display: alternate identifiers and keywords

- setup.py
- tests/unit/redirector/test_redirection.py
- zenodo/modules/redirector/__init__.py
- zenodo/modules/redirector/config.py
- zenodo/modules/redirector/views.py
* Adds the redirections needed in order to make the previous Zenodo
links compatibles. (closes #427)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> global: addition of legacy redirections

- zenodo/modules/theme/templates/zenodo_theme/security/register_user.html
"Uploads gets a DOI" -> "Uploads get a DOI"
> Fix grammar mistake on the sign up page

- docker/nginx/nginx.conf
A ";" is misplaced.
Docker frontend container will not start with this problem.
> Fix nginx configuration error

- run-tests.sh
- tests/unit/deposit/test_api_files.py
- tests/unit/deposit/test_communities_merging.py
- tests/unit/deposit/test_deposit_api.py
- tests/unit/helpers.py
- zenodo/modules/deposit/api.py
Fixes an issue with internal metadata fields such as _oai, _files getting overwritten after editing of a pre-migration record.
> deposit: published record fields preservation fix

- tests/unit/auditor/test_oai.py
- tests/unit/conftest.py
- tests/unit/deposit/test_communities_merging.py
- zenodo/modules/deposit/api.py
- zenodo/modules/deposit/config.py
* Fixes the issue with auto-requesting of a community that was added in the meantime.
> communities: communities redundant auto-request bugfix

- Dockerfile
* Fixes look-and-feel of the Docker-built Zenodo site by installing appropriate
npm package versions.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docker: npm package installation fix

- Dockerfile
- docker/es/Dockerfile
* Installs Elasticsearch mapper-attachments plugin, fixing loading of demo
records.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docker: Elasticsearch mapper-attachments plugin

- setup.py
- tests/unit/records/test_schemas_legacyjson_load.py
- zenodo/modules/records/serializers/fields/doi.py
- zenodo/modules/records/serializers/fields/html.py
- zenodo/modules/records/serializers/fields/persistentid.py
- zenodo/modules/records/serializers/fields/sanitizedunicode.py
- zenodo/modules/records/serializers/fields/sanitizedurl.py
- zenodo/modules/records/serializers/schemas/common.py
- zenodo/modules/records/serializers/schemas/legacyjson.py
* Adds custom a custom marshmallow string field that washes strings
using `ftfy` and a set of unwanted Unicode characters. (closes #917)
> deposit: unicode sanitization

- zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
In the current upload form, the DOI description does not clearly explain the consequences of entering a custom DOI (e.g. it can be edited later) vs. leaving the DOI field empty for the Zenodo to register automatically. 
The lack of explanation raises many doubts, for example: "If I copy and paste a wrong DOI, will I be able to fix my mistake later?", "Can I upload a preprint of a paper, which will be assigned a DOI by the publisher later?," or "can I edit a DOI issued by Zenodo". Moreover, uploaders can easily overlook the fact that a Zenodo DOI cannot be changed (because they might miss the warnings elsewhere) and make "erroneous" submissions, hence get frustrated.
We (Maria de Maeztu Unit of Excellence Coordination in Universitat Pompeu Fabra, Barcelona) contacted Zenodo a couple of …
> Improve the DOI item description

- requirements.txt
This should fix the readthedocs builds.
Remove the stale version: http://docs.readthedocs.io/en/latest/faq.html?highlight=stale#deleting-a-stale-or-broken-build-environment
> installation: removed redundant dependency

- INSTALL.rst
Change `zenodo migration reindex recid` to `zenodo migration reindex -t recid`
> INSTALL.rst : Correct the command to reindex the migrations

- INSTALL.rst
The fixtures loadlicenses, fixtures loadfp6grants are there in init.sh so doesn't need here.
> Updated Install.rst

- zenodo/config.py
* Fixed typo in zendo.config.py.
Solves #790.
> search: typo fix

- docker-compose.yml
* Fixes issue with container creation for newer versions of the
rabbitmq docker image.
> docker: remove read_only from rabbitmq

- tests/unit/records/test_schemas_csl.py
- zenodo/modules/records/data/objecttypes.json
* Fixes issue with software having "[dataset]" in the default ciation.
Based on discussion with CSL developers, the best is to use article
for software instead of dataset as then the type is not included in
the citation.
* Fixes issue with reports not having a DOI in the default APA citation.
(closes #1074)
> records: citation fixes

- tests/unit/communities/test_communities_api.py
- tests/unit/deposit/test_api_buckets.py
- tests/unit/deposit/test_deposit_index.py
- tests/unit/records/test_records_relations_serialization.py
- zenodo/modules/deposit/api.py
- zenodo/modules/deposit/errors.py
- zenodo/modules/github/api.py
* Disallows publishing a new version with files which
already were published in one of the previous record's versions.
> versioning: publishing protection from repeated files

- tests/unit/communities/test_communities_api.py
- tests/unit/deposit/test_api_buckets.py
- tests/unit/deposit/test_deposit_index.py
- tests/unit/records/test_records_relations_serialization.py
- zenodo/modules/deposit/api.py
- zenodo/modules/deposit/errors.py
- zenodo/modules/deposit/views.py
- zenodo/modules/github/api.py
* Automatically upgrades a non-versioned GitHub records to versioning
on new releases.
* Fixes a bug with record versioning upgrade.
> versioning: GitHub non-versioned releases upgrades

- .travis.yml
* Skips the builds for branches (tags) which starting with 'deploy-'.
> installation: added skipping of deploy tags builds

- requirements.pinned.txt
- requirements.txt
- setup.py
* Fixes issue which prevents date granularity harvesting. Root cause
was breaking change in datetime validation introduced between
marshamllow 2.13.4 and 2.13.5.
> oaiserver: fix date granularity harvesting

- tests/unit/records/test_schemas_dc.py
- zenodo/modules/records/serializers/schemas/dc.py
* Reorders serialized identifiers to display the Zenodo URL first.
> serializers: identifier order fix for oai_dc

- zenodo/config.py
* Changes the MathJax CDN to use cdnjs.cloudflare.com. (closes #1053)
> config: MathJax CDN update

- zenodo/modules/deposit/static/templates/zenodo_deposit/list.html
- zenodo/modules/deposit/templates/zenodo_deposit/edit.html
There are some unresolved UI problems.
1. Disable the apply button before the extraction is completed. `ng-disabled` does not work as I expected.
2. Close the modal when I apply the changes.  I use `ng-click="applyMetadata();$hide()" ` in the code. But it seems `$hide()` is not executed.
> metadata-extractor: extractor metadata modal

- zenodo/modules/deposit/static/templates/zenodo_deposit/select.html
* Removes blank placeholder for select form fields, because of bad
behaviour in IE 11. (closes #1319)
> deposit-ui: fix IE 11 compatibility

- tests/unit/records/test_schemas_schemaorg_jsonld.py
- zenodo/modules/records/serializers/schemas/schemaorg.py
* Record DOI is now serialized both as '@id' and 'identifier'.
> records: addition of 'identifier' to the schema.org serialization

- tests/unit/conftest.py
- tests/unit/exporter/conftest.py
- tests/unit/sitemap/test_sitemap_generator.py
- zenodo/modules/exporter/streams.py
- zenodo/modules/exporter/tasks.py
- zenodo/modules/exporter/writers.py
- zenodo/modules/records/serializers/schemas/common.py
- zenodo/modules/records/serializers/schemas/json.py
* Removes necessity to have a request context in order to generate
URLs when serializing records.
> exporter: request context independent url gen

- tests/unit/stats/test_stats_aggs.py
- zenodo/config.py
- zenodo/modules/records/serializers/schemas/datacite.py
- zenodo/modules/stats/__init__.py
- zenodo/modules/stats/ext.py
- zenodo/modules/stats/proxies.py
- zenodo/modules/stats/registrations.py
* Uses a custom Elastricsearch client with increased request timeout
when processing aggregations.
* Decreases days batch size for aggregation queries (creating buckets
for 1 day vs. 7 days).
> stats: aggregations fault tolerance increase

- zenodo/modules/records/templates/zenodo_records/box/versions.html
* Use appropriate field for version number
when versions are more than five.(closes #1478)
> records-ui: use appropriate field for version

- zenodo/modules/deposit/static/js/zenodo_deposit/filters.js
- zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html
* Disable the publish button and display appropriate
message in the case of selected but not uploaded files
or if no selected files are present. (closes #1412)
> deposits-ui: disable publish button on files

- zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json
- zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
- zenodo/modules/records/data/objecttypes.json
* close #1726
In order to review the choices made for the different fields, here is the list of the specifications for each of them
``"schema.org":`` https://schema.org/docs/full.html
``"datacite":`` https://schema.datacite.org/meta/kernel-4.2/doc/DataCite-MetadataKernel_v4.2.pdf
``"openaire":``  from https://github.com/zenodo/zenodo/issues/1270
``"csl":`` from https://github.com/citation-style-language/documentation/blob/master/specification.txt
Appendix III - Types
--------------------
-  article
-  article-magazine
-  article-newspaper
-  article-journal
-  bill
-  book
-  broadcast
-  chapter
-  dataset
-  entry
-  entry-dictionary
-  entry-encyclopedia
-  figure
-  graphic
-  interview
-  legislation
-  legal\_case
-  manuscript
-  map
-  motion\_picture
-  musical\_score
-  pamphlet …
> types: add two publication subtypes

- zenodo/modules/support/templates/zenodo_support/contact_form.html
* Fixes an issue where logged in users without a full name in the
user profile could not send a support request due to a disabled
required field in the form.
> support: fix problem for users without full name

- zenodo/modules/github/api.py
Currently, when populating the metadata of the new release we are omitting the field ```communities``` which causes, due to ```_sync_communities```, the removal of the communities from every previous version.
Issue: https://github.com/zenodo/zenodo/issues/1795
> github: fix communities getting removed from github records

- README.rst
- docs/conf.py
- zenodo/modules/theme/templates/zenodo_theme/footer.html
- zenodo/modules/theme/templates/zenodo_theme/security/register_user.html
Hello!
This updates some links the HTTPS version of sites that either forward automatically, or have it separately but working. Similarly, the old `dx.doi.org` is redirected automatically, but let's switch it to `https://doi.org` at the source.
About the `...API update`: In case the tests should cover the non-HTTPS links as well, please let me know and I'll revert those lines. If you on the other hand agree to only continue testing the HTTPS links, I would push another (few) commit(s). `d-nb.info` for example would be securely linked to at the source.
Cheers :-)
> Secure & update hyperlinks

- zenodo/modules/deposit/static/js/zenodo_deposit/filters.js
- zenodo/modules/deposit/static/templates/zenodo_deposit/list.html
- zenodo/modules/deposit/templates/zenodo_deposit/edit.html
- zenodo/modules/theme/templates/zenodo_theme/footer.html
* Changes display file size measurement unit to ^10 instead of ^2
* Adds additional support link in the footer
> deposit-ui: makes the displayed size limit dynamic

- zenodo/modules/deposit/static/json/zenodo_deposit/deposit_form.json
- zenodo/modules/records/serializers/fields/html.py
- zenodo/modules/records/templates/zenodo_records/record_detail.html
- zenodo/modules/theme/static/scss/record.scss
closes #2147 
Allows HTML tables to be used in a record's description through the API or CKEditor in the deposit form
> deposit: allow HTML tables

- tests/unit/records/test_schemas_datacite.py
- zenodo/modules/records/serializers/schemas/datacite.py
* Fixes an issue where if the `thesis` field is not filled-in the
DataCite serializer silently skips contributors serialization.
* Closes #2326.
> schemas: fix DataCite contributors serialization

- zenodo/config.py
- zenodo/modules/spam/models.py
- zenodo/modules/spam/templates/zenodo_spam/safelist/admin.html
- zenodo/modules/spam/views.py
- Added another try-except, but seems weird to me since it's already supposed to be handled in the method
- Filter by weeks
- Went around this by adding a field to select how many users we want to be displayed
- Descriptions don't seem to work well for this, maybe a copy button could work better
- Selection is triggered when eg. we click on the user profile or translate links
> spam: safelist admin panel optimizations

- zenodo/modules/frontpage/templates/zenodo_frontpage/index.html
This fixes the deprecation warning, there is another console-logged comment regarding the Twitter feed, but it seems irrelevant to this issue.
> homepage: update twitter feed to latest version

- zenodo/modules/records/views.py
- zenodo/modules/spam/tasks.py
- zenodo/modules/spam/utils.py
- zenodo/modules/spam/views.py
Running `pydocstyle zenodo tests docs` doesn't generate any warnings anymore.
> pydocstyle: fix styling errors
